key_path           = "/tmp"
project            = "ashwinknaik-314910"
keyring_name       = "keyring-ex-1230989"
keyring_location   = "global"
keyring_key_name   = "cryptokey-example"
keyring_import_job = "my-import-job"