key_path           = "/tmp"
project            = "ashwinknaik-314910"
keyring_name       = "keyring-ex-99999"
keyring_location   = "global"
keyring_key_name   = "cryptokey-example1"
keyring_import_job = "new-import-job"